//
// Created by Iván Canales Martín on 2019-01-08.
//

#ifndef OBJECT_DETECTION_AND_CLASSIFICATION_DATALOADER_H
#define OBJECT_DETECTION_AND_CLASSIFICATION_DATALOADER_H


class DataLoader {

};


#endif //OBJECT_DETECTION_AND_CLASSIFICATION_DATALOADER_H
